name: 'meshcloud - Setup collie'
description: 'Sets up collie cli in your GitHub Actions workflow.'
inputs:
  collie-version:
    description: 'The version of collie cli that this action will set up.'
    default: 'latest'
    required: false
runs:
  using: "composite"
  steps:
    - name: Create local bin folder and add it to Path
      shell: bash
      run: |
        mkdir -p ~/.local/bin
        echo "~/.local/bin" >> $GITHUB_PATH
    - name: Download collie cli
      shell: bash
      run: |
        if [ ${{ inputs.collie-version }} = 'latest' ]; then
          wget --no-verbose https://github.com/meshcloud/collie-cli/releases/latest/download/collie-x86_64-unknown-linux-gnu.tar.gz -P ~/.local/bin
        else
          wget --no-verbose https://github.com/meshcloud/collie-cli/releases/${{ inputs.collie-version }}/collie-x86_64-unknown-linux-gnu.tar.gz -P ~/.local/bin
        fi
        tar -zxf ~/.local/bin/collie-x86_64-unknown-linux-gnu.tar.gz -C ~/.local/bin
        mv ~/.local/bin/collie-x86_64-unknown-linux-gnu ~/.local/bin/collie
        chmod +x ~/.local/bin/collie
