name: 'meshcloud - Setup unipipe'
description: 'Sets up unipipe cli in your GitHub Actions workflow.'
inputs:
  unipipe-version:
    description: 'The version of unipipe cli that this action will set up.'
    required: true
    default: 'latest'
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p ~/.local/bin
        echo "~/.local/bin" >> $GITHUB_PATH
    - name: download-unipipe-cli
      run: |
        if [ ${{ inputs.unipipe-version }} = 'latest' ]; then
          https://github.com/meshcloud/unipipe-service-broker/releases/latest/download/unipipe-cli-x86_64-unknown-linux-gnu -P ~/.local/bin
        else
          wget --no-verbose https://github.com/meshcloud/unipipe-service-broker/releases/${{ inputs.unipipe-version }}/unipipe-cli-x86_64-unknown-linux-gnu -P ~/.local/bin
        fi
        mv ~/.local/bin/unipipe-cli-x86_64-unknown-linux-gnu ~/.local/bin/unipipe
        chmod +x ~/.local/bin/unipipe
